export default [
    "Sender must comply with the Know Your Customer (KYC) form, present valid identification, and must subscribe to the AMLC rules and regulations and other applicable laws in making the transaction.",
    "The Sender must register the fullname of the receiver including full middle name. Should the sender fail to give the full middle name of the receiver, it shall b e considered a waiver on this part to include his information in verifying the transaction.\n\nMLFSI shall not be held liable for any paid transactions to a receiver whoe full middle name information was waived by the Sender.\n\nIncorrect Spelling of the receiver's name(s) may cause delay in paying out the transaction.",
    "The Sender hereby agrees that the transaction shall be released to the claimant receiver if the latter can present the correct Kwarta Padala Transaction Number (KPTN) and comply with the valid ID, KYC and all other requirements as may be required by law.",
    "The Sender must relay to the receiver the complete and correct KPTN and must advise the receiver to bring a valid ID for additional verification purposes.",
    "The Sender may waive the age requirement of the receiver. However, a minor receiver can only claim the money provided said minor is a relative of the sender to the 4th civil degree or godchild / ward / beneficiary of the sender or whose relationship with the sender is such that it does not violate the Child Trafficking Law.\n\nThe said minor receiver must comply with the identification requirements mentioned herein.\n\nMinors below 12 years old must be accompanied by his / her guardian. The said guardian must comply with the requirements in Item No.3 herein.",
    "The money is available for pickup in any MLFSI subject to hours of operation of the selected payout branch including closures without prior notice, its communications facility, its connectivity to the ML Wallet and MLKP Systems, and other conditions, including but not limited to power and telecommunications failure, computer or gadget failure, inclement weather and the like.",
    "Should the sender decides to cancel sendout, he / she must submit a written request to MLFSI for the cancellation of the said transaction. MLFSI will refund the principal amount of the money transfer only. MLFSI will refund the charges upon written request of the sender, only if the money transfer is not available at the recipient within seven (7) days from the time it was sent.\n\nTo the extent allowed by law, MLFSI may deduct a service fee of FIVE HUNDRED PESOS (Php500) per month from money transfer that are not picked up after one month from the time it was sent.",
    "Changes to the original entries of the sendout will be made only at any MLFSI branches.",
    "In cae of delay, non-payment or underpayment of this money transfer whether by fault or negligence of the company or its employees, neither shall be liable for damages beyond the sum of FIVE THOUSAND PESOS (Php5,000), in addition to the refund  of the principal amount of the money transfer and the service fee.\n\nIn no event will the company or its employees be liable for any indirect, special, incidental or consequential damages.",
    "MLFSI reserves the right to deactivate the customer account in cases of three times login failure, however, the customer may request activation by calling our Customer Care.",
    "MLFSI may not accept, process or pay any money transfer that any of them determines, in their sole discretion, to be in violation of any MLFSI policy or applicable law.",
    "All claims or suits regarding this transaction shall be filed in the courts of Ceby City only."
]