import {createTypes} from 'reduxsauce'

export default createTypes(` 
  STARTUP

  SET_IS_FIRST_TIME
  SET_IS_USING_TOUCH_ID
  SET_HAS_SEEN_SENDMONEY_ONBOARDING
  SET_HAS_SEEN_RECEIVEMONEY_ONBOARDING
  SET_HAS_SEEN_WITHDRAWCASH_ONBOARDING
  SET_HAS_SEEN_PAYBILLS_ONBOARDING
  SET_HAS_SEEN_BUYLOAD_ONBOARDING

  LOGIN
  LOGOUT

  SET_USER
  CLEAR_USER

  NETWORK_SUCCESS
  NETWORK_FAILURE

  SET_ATTACHED_FILES
  CLEAR_ATTACHED_FILES

  SET_NOTIFICATIONS
  CLEAR_NOTIFICATIONS
`)