import {createTypes} from 'reduxsauce'

export default createTypes(` 
  STARTUP

  SET_IS_FIRST_TIME
  SET_IS_USING_TOUCH_ID
  SET_HAS_SEEN_SENDMONEY_ONBOARDING
  SET_HAS_SEEN_RECEIVEMONEY_ONBOARDING
  SET_HAS_SEEN_WITHDRAWCASH_ONBOARDING
  SET_HAS_SEEN_PAYBILLS_ONBOARDING
  SET_HAS_SEEN_BUYLOAD_ONBOARDING

  ADD_WALLET_RECEIVER
  UPDATE_WALLET_RECEIVER
  DELETE_WALLET_RECEIVER
  REFRESH_WALLET_FAVORITES

  ADD_KP_RECEIVER
  UPDATE_KP_RECEIVER
  DELETE_KP_RECEIVER

  ADD_BANK_PARTNER
  UPDATE_BANK_PARTNER
  DELETE_BANK_PARTNER

  ADD_ELOAD_RECEIVER
  UPDATE_ELOAD_RECEIVER
  DELETE_ELOAD_RECEIVER

  LOGIN
  LOGOUT

  SET_USER
  UPDATE_BALANCE
  CLEAR_USER

  NETWORK_SUCCESS
  NETWORK_FAILURE

  SET_ATTACHED_FILES
  CLEAR_ATTACHED_FILES

  SET_NOTIFICATIONS
  CLEAR_NOTIFICATIONS
`)